services:
  - type: web
    name: members
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi
    preDeployCommand: |
      cd backend
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
      echo "from django.contrib.auth.models import User;
      User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')" | python manage.py shell
