# Generated by Django 5.2.1 on 2025-07-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_members_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
