# Generated by Django 5.2.1 on 2025-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_members_dob_members_email_members_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
